### ISSUE TITLE
Errors while building on Ubuntu 18.04 on WSL2 with Rust nightly

### ISSUE THREAD

**Issue by playerdefault** [samuela/rustybox#30] opened 2020-05-30 22:43 UTC
Trying to build it in WSL2 gives the error: 
```
error: legacy asm! syntax is no longer supported
archival/dpkg.rs:2451:3
     |
2451 |   asm!("" : : : "memory" : "volatile");
     |   ----^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |   |
     |   help: replace with: `llvm_asm!
```
in a bunch of places (422 errors)

Here's the relevant system information:
Linux Version: 4.4.0-18362-Microsoft x86_64 x86_64 x86_64 GNU/Linux
Ubuntu Version: Ubuntu 18.04.4 LTS
Windows Version: Windows 10 Pro 1909 (v. 18363.836)
Rust version: 1.45.0-nightly (4bd32c980 2020-05-29)

**Comment by samuela** [comment] 2020-05-31 02:49
I can reproduce. It looks like we're getting bit by https://github.com/rust-lang/rfcs/pull/2843...

**Comment by samuela** [comment] 2020-05-31 02:55
Ok, should be fixed with https://github.com/samuela/rustybox/commit/0d2201eece506e88f71d0e251346bb3e92bb7aef! Let me know if that's not the case for you!

**Closed as completed by samuela** 2020-05-31 02:55 UTC

**Comment by playerdefault** [comment] 2020-05-31 05:07
Confirmed building for rustc version `1.45.0-nightly (74e804683 2020-05-30)` on posted environment.
![image](https://user-images.githubusercontent.com/26647804/83344921-e25e3480-a32a-11ea-9def-d42b3ca91e5b.png)

**Comment by samuela** [comment] 2020-05-31 06:11
Niiiice!
